name: imaxip
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  sqflite: ^2.4.2
  path_provider: ^2.1.5
  flutter_screenutil: ^5.9.3
  http: ^1.4.0
  provider: ^6.1.5
  shared_preferences: ^2.5.3
  cupertino_icons: ^1.0.8
  screen_brightness: ^2.1.6
  saver_gallery: ^4.0.1

  # VLC Oynatıcı paketi eklendi
  flutter_vlc_player: ^7.4.3

  path: any
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true